### ISSUE TITLE
update readme with amendment proposal & approval process and how to do pull requests

### ISSUE THREAD

**Issue by chrissprague** [rit-csc/constitution#5] opened 2015-01-25 19:09 UTC
See also <b>https://github.com/rit-csc/constitution/issues/3</b>

**Comment by khipkin** [comment] 2015-03-09 16:15
Duplicate of issue #3.

**Closed as completed** 2015-03-09 16:15 UTC
Labels: enhancement

**Comment by chrissprague** [comment] 2015-03-09 19:18
@khipkin oh. true
